### ISSUE TITLE
Search Step Size with TPE

### ISSUE THREAD

**Issue by Simplesss** [VDIGPKU/CMUA-Watermark#1]
First of all, thank you very much for your contribution. I plan to reproduce your code, but due to machine limitations, I cannot run Search Step Size with TPE. Can you provide the searched step size?

**Comment by Huaxingweichen** [comment]
Thank you for your interest in our work.
I strongly suggest you to decrease the batch size when searching the step sizes, since the best step sizes are related to the batch size.

**Comment by delong-zhu** [comment]
> First of all, thank you very much for your contribution. I plan to reproduce your code, but due to machine limitations, I cannot run Search Step Size with TPE. Can you provide the searched step size?

Hello, I'm sorry to bother you. Have you reproduced this paper now? I have some questions to ask you.
